name: setgreet
description: Official Flutter SDK for Setgreet - Mobile app user onboarding and engagement platform
version: 0.1.0
homepage: https://setgreet.com
repository: https://github.com/setgreet/setgreet-flutter-sdk
issue_tracker: https://github.com/setgreet/setgreet-flutter-sdk/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.setgreet.flutter
        pluginClass: SetgreetPlugin
      ios:
        pluginClass: SetgreetPlugin

topics:
  - setgreet
  - flutter
  - sdk
  - mobile-app
  - onboarding
